### ISSUE TITLE
Switching to cloudfare kv store to real db

### ISSUE THREAD

**Issue by Gozala** [ipfs-shipyard/nft.storage#183] opened 2021-06-14 16:38 UTC
Creating this so we can retroactively document how did we end up deciding to use fauna db.

**Comment by alanshaw** [comment] 2021-06-15 16:45
@gozala is this a duplicate of https://github.com/ipfs-shipyard/nft.storage/issues/183 ?

**Comment by Gozala** [comment] 2021-06-16 06:17
> @Gozala is this a duplicate of #183 ?

No it is #183 itself 😂

**Comment by Gozala** [comment] 2021-06-16 21:44
There are few things that do not fit well across nft.storage and niftysave DB schemas that I'd like to call out / discuss.

1. Given that niftysave each resource has has links to metadata that referred to it, our `addDirectory` and `addBlob` endpoints no longer fit that model well. It introduces some resources that have no metadata associated with them. `addDirectory` is the worst, because we still have a single cid to tie individual resources.

**Comment by Gozala** [comment] 2021-06-17 17:22
Right now our code is really hand-wavy about the `size` it can be file size or dag size etc... We should figure out what we care about storing and when. cluster add provides size and bytes but we don't know which one to use.

**Comment by dchoi27** [comment] 2021-08-17 15:26
Closing in favor of #181

**Closed by dchoi27** 2021-08-17 15:26 UTC
